# Generated by Django 2.1.3 on 2021-03-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
