# Generated by Django 2.1.3 on 2021-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karmaapi', '0002_auto_20210306_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(editable=False, max_length=150)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('alternate_mobileno', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
